### ISSUE TITLE
Duplicate items in "Recent activities" coming from GitHub integration

### ISSUE THREAD

**Issue by flodolo** [stasm/alfred#33]
Not sure when it started, but in the last couple of weeks I noticed that I'm getting duplicate items from GitHub pull requests.

**Comment by flodolo** [comment]
Uhm, it might just be me not being smart (open + close, not duplicates).
Will reopen if that's not the case.

**Comment by stasm** [comment]
@flodolo I still think the current approach (open + close) doesn't scale well. Any ideas how to solve this?

**Comment by flodolo** [comment]
Having no clue how the app actually works, a clean approach would be to store the PR link instead of just creating a new entry when the PR is opened, and update the existing entry when the PR is closed. 
If, in the meantime, the "opened pr" item has been eliminated, it would be OK to just create the "closed PR".

**Comment by stasm** [comment]
That's a good suggestion, thanks! The app supports a way to update a status of an item while keeping its history. I think it should be possible to use this to change an item about an opening of a github issue into an item about closing or merging.
